### ISSUE TITLE
Minor issue:  'parameterized' is linked but the link does not point to anything.

### ISSUE THREAD

**Issue by AramZS** [csharrison/conversion-measurement-api#10]
In README.md, under `Permission Delegation` the term `parameterized` is linked, presumably intended to link to a definition? The link does not seem to go anywhere. The documentation here would be clearer if the link was either removed or fixed.

**Comment by csharrison** [comment]
Thank you for catching this! The link is meant to point to https://github.com/w3c/webappsec-feature-policy/issues/163. I'll fix it right away.
