### ISSUE TITLE
Consider renaming "last-clicked" to "credit"

### ISSUE THREAD

**Issue by johnivdel** [csharrison/conversion-measurement-api#16]
The explainer currently annotates all conversion reports with a "last-clicked" query param. Consider changing this to "credit" to make the API agnostic to the attribute model implemented.

A last clicked model could operate within this API by setting credit=1 for the last clicked impression and 0 for the rest.

**Comment by csharrison** [comment]
This SGTM, this gives the API a bunch more flexibility in case we want to extend in the future.
