### ISSUE TITLE
Converting multiple times from the same impression

### ISSUE THREAD

**Issue by csharrison** [csharrison/conversion-measurement-api#4]
There are a couple potential ways to solve this issue:

1. Allow any given impression to convert some small number of times - this reveals more information from the advertiser.

2. Allow multiple conversions within the same reporting epoch a method of local aggregation.

3. Give every conversion a priority (similar https://wicg.github.io/ad-click-attribution/index.html#terminology), so high priority conversions will supersede low priority ones. Similar to (2) if your aggregation function is something like MAX.

**Comment by csharrison** [comment]
4. Same as (1), but subsequent conversions get coarser information than the first.

**Comment by minghaocwang** [comment]
hi @csharrison, among all these 4 options above, is it decided which option will be used/implemented in https://github.com/csharrison/conversion-measurement-api ?
If you are leaning to option 2, then what kind of local aggregation in your mind?

**Comment by csharrison** [comment]
This issue is a bit obsolete, so it should be closed. We ended up landing on option (1) for simplicity for now, by letting each impression convert some small number of times (e.g. 3).
