### ISSUE TITLE
Define impression tags more

### ISSUE THREAD

**Issue by ehsan** [csharrison/conversion-measurement-api#7]
https://github.com/csharrison/conversion-measurement-api#permission-delegation refers to "impression tags" but doesn't describe the term.  I had a difficult time understanding the second paragraph, it would be nice to expand that section a little bit.  Thanks!

**Comment by csharrison** [comment]
By "impression tags" I just meant "impression anchor tags" described in the above section. I can attempt to flesh this out a bit.

**Comment by csharrison** [comment]
Ehsan, let me know if the commit above helps with clarity here.

**Comment by ehsan** [comment]
Yes, thank you!

**Comment by csharrison** [comment]
Awesome, let me close this out then. Feel free to re-open if there's more that needs to be done.
